### ISSUE TITLE
bash.exe: warning: could not find /tmp, please create!

### ISSUE THREAD

**Issue by MartinBuchmann** [portacle/portacle#101]
When I try to push my local commit to origin/master using magit I get the above error. I do not know where Windows is expecting its tmp directory etc.

Could you advise where to create it or configure portacle in such way it uses Windows' standard directory?

**Comment by MartinBuchmann** [comment]
I understand, thanks!

**Comment by argentcorvid** [comment]
adding a /tmp folder to the top-level portacle folder (portacle root) will make it shut up about it
