### ISSUE TITLE
Emacsd: Slime-company does not work

### ISSUE THREAD

**Issue by triskaj** [portacle/portacle#103]
The problem is that `portacle-slime` package is loaded before `portacle-company` package where `slime-company` symbol is pushed into `portacle-slime-contribs`. However, slime is setupped inside `portacle-slime` package using `portacle-slime-contribs`. 

Therefore, I suggest either to setup slime in some hook after the packages are loaded or to explicitly add `slime-company` symbol into `portacle-slime-contribs` list inside `portacle-slime` package.

**Comment by Shinmera** [comment]
I think it used to work how you suggest, but a regression creeped in when the Sly switch was added. Thanks for the report!
