### ISSUE TITLE
Invalid regexp: "Invalid back reference" on Windows 10 

### ISSUE THREAD

**Issue by jezze-d** [portacle/portacle#106]
Portacle seems to work fine on Windows 10 for the most part, but whenever I use C-x C-f to open a new file or C-x C-s to save, the following error occurs in the mini-buffer: "Invalid regexp: "Invalid back reference"". The end result is that files cannot be opened nor saved. The same error occurs if I want to quit using C-x C-c or use even the menu option so I'm forced to use Task Manager to kill Emacs.

**Comment by Shinmera** [comment]
This is an issue in an elisp package that I do not control. A patch has been submitted, but has not been merged in yet, unfortunately. See https://gitlab.com/bennya/shrink-path.el/merge_requests/1

**Comment by Zulu-Inuoe** [comment]
As a bandaid, you should be able to work around this by setting your HOME environment variable such that it uses forward slashes rather than backslashes, and doesn't end in a trailing slash:
eg instead of 
`HOME=C:\Users\Zulu\`
use
`HOME=C:/Users/Zulu`

It should at least work around this for now.

**Comment by jezze-d** [comment]
The suggested work around doesn't seem to change anything. I'm giving up on Windows and going back to Linux were all the Lisp development tools just work; Linux is so much easier I don't know why I even bother with Windows.

**Comment by Shinmera** [comment]
Reopening since the issue is real.

**Comment by Shinmera** [comment]
Tracking: seagle0128/doom-modeline#123

**Comment by Shinmera** [comment]
Fixed via doom-modeline patch. Running portacle-update, or updating via package-list-packages should fix this.
