### ISSUE TITLE
Portacle for 32bits 

### ISSUE THREAD

**Issue by noloop** [portacle/portacle#107]
Is there a way to compile the portacle to run on 32bit systems? because I saw that emacs works for 32bit and SBCL as well. Is there anything in portacle that limits compilation to 32bit?

**Comment by Shinmera** [comment]
You can try building it yourself. The instructions are in the readme.

I just don't ship it because there's very few users stuck on x86.

**Comment by noloop** [comment]
@Shinmera I could build them. I'm not really sure how to build, would it just change the 64-bit packages to 32-bit and should it work, or do I need to do something else?

**Comment by Shinmera** [comment]
It might just work.
