### ISSUE TITLE
Cant open the application on Mojave

### ISSUE THREAD

**Issue by dopatraman** [portacle/portacle#108]
I'm trying to open the Portacle .app file on Mojave, and while I don't get an error, the application never opens. I've set the security permissions to allow the app to be opened. It's strange -- I see the dock flicker for a second but the Portacle window does not open. 

**UPDATE**

I dug around the project and found the `sbcl` executable. When I open it, I see the following output:
```
fatal error encountered in SBCL pid 50589(tid 0xd4425c0):
can't find core file at /usr/local/lib/sbcl//sbcl.core
```
Does this mean I need to have SBCL installed on my machine prior to using Portacle?

**Comment by Shinmera** [comment]
Did you follow the [instructions on the website](https://portacle.github.io/#get-mac) carefully?

**Comment by dopatraman** [comment]
Meaning move it to another directory and then back? Yes.

**Comment by Shinmera** [comment]
Well, in that case it crashes somewhere during Emacs startup. The SBCL executable you found is not the right one (try `portacle/mac/bin/sbcl`). You do not need to have SBCL installed, that would defeat the entire purpose of this.

Can you run `portacle/mac/bin/emacs` from the command line and report what, if anything, it shows?

**Comment by nigelbrown** [comment]
I'm running Portacle on my Macbook with Mojave with no problems.

**Comment by dopatraman** [comment]
I tried it again, and it worked.

But strangely... i cannot find the `portacle/mac/bin/emacs` executable...
