### ISSUE TITLE
Unpacking Error 'can not create hardlink'

### ISSUE THREAD

**Issue by noloop** [portacle/portacle#113]
When I'm unpacking the portacle linux tar.xy I get:

`tar: can't create hardlink 'portacle/lin/bin/hunspell' to 'portacle/lin/bin/ag'`

when I check there does not exist file `portacle/lin/bin/hunspell`

When I try to run the portacle I get:

```
$ cd portacle                             
$ chmod +x portacle.run                    
$ ./portacle.run     
./portacle.run: 7: ./portacle.run: /data/data/com.termux/files/home/portacle//lin/launcher/portacle: not found
```

I wanted to use it in termux.

**Comment by noloop** [comment]
I solved the hard link problem with ´proot --link2symlink´ but it still does not work:

ˊˊˊ
$ cd portacle/                                  
$ chmod +x portacle.run                         
$ ./portacle.run                            /data/data/com.termux/files/home/portacle//lin/launcher/portacle: 1: /data/data/com.termux/files/home/portacle//lin/launcher/portacle: Syntax error: word unexpected (expecting ")")
ˊˊˊ

**Comment by Shinmera** [comment]
termux? Isn't that an Android thing? What makes you think Portacle would work on Android?

**Comment by noloop** [comment]
@Shinmera emacs works on termux, so I found the portacle too.

**Comment by Shinmera** [comment]
Portacle has no ARM release and is not officially supported on Android either.

**Comment by noloop** [comment]
From what I saw SBCL now works for ARM. The emacs also. What else in the portacle might not work in ARM?

**Comment by blindglobe** [comment]
Userland (where you can run a Debian-baded SBCL , Emacs, and SLIME) might be a option if you want portacle on your Android phone. I use it when I have an idea , but phone displays are tiny.  Haven't tried portacle, just my standard Debian setup.

**Comment by noloop** [comment]
@blindglobe Can you tell me how you did to get SBCL working? I tried here and I can not get it to work.

**Comment by noloop** [comment]
@blindglobe I managed to make it work on Userland-ArchLinux, emacs + SBCL + quicklisp + Slime, very good now I only need to buy a small keyboard for this phone.
