### ISSUE TITLE
Editing Commands...

### ISSUE THREAD

**Issue by gambledrum** [portacle/portacle#116]
Is there a reason why I can't use Shift/Ctrl with the arrows keys in order to select text in a text (lisp) file?  I can select text with a mouse, but not using the regular keyboard commands.
How can I get this to work?
I've can do this in regular Emacs.
Is this another customization in the .el file?

**Comment by Shinmera** [comment]
We don't explicitly disable it, so re-enabling shift selection mode should help.

Please learn about Emacs customisation yourself. Google has tons of resources on how to get things done and this bug tracker is not the right place to get general Emacs help.
