### ISSUE TITLE
Emacs closing after entering "~a~

### ISSUE THREAD

**Issue by CactoBoy** [portacle/portacle#117]
Hi, Emacs is closing when I enter `"~a~` at the Sly REPL. Seems to be the same no matter what character I type between tildes. Working ok with Slime.

Steps to reproduce:
- Start Portacle (think it's 1.3, but how can I confirm this?), no changes to init files
- Type " (only one char, no new line)
- Type ~
- Type a
- Type ~
- Emacs closes

OS: Peppermint Linux v9

**Comment by phoe** [comment]
I can reproduce this. Console logs:

```
$ ~/Downloads/portacle/portacle.run 
Warning: arch-dependent data dir '/home/linus/portacle/lin/emacs/libexec/emacs/26.1/x86_64-pc-linux-gnu/': No such file or directory
Warning: Lisp directory '/home/linus/portacle/lin/emacs/share/emacs/26.1/lisp': No such file or directory
/usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so: undefined symbol: g_log_structured_standard
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

(Portacle:29567): GdkPixbuf-WARNING **: Error loading XPM image loader: Image type 'xpm' is not supported
Inconsistency detected by ld.so: dl-open.c: 689: _dl_open: Assertion `_dl_debug_initialize (0, args.nsid)->r_state == RT_CONSISTENT' failed!
```

**Comment by CactoBoy** [comment]
Just wanted to confirm what @phoe said. I get the same error in the console:

`Inconsistency detected by ld.so: dl-open.c: 689: _dl_open: Assertion `_dl_debug_initialize (0, args.nsid)->r_state == RT_CONSISTENT' failed!`

**Comment by metayan** [comment]
No problem on macOS.

**Comment by Shinmera** [comment]
I remember something like this happening before where sly for some reason triggers a shared library load.

Can you paste the log of `strace -f -e trace=open ./portacle.run &> a.log`?

**Comment by CactoBoy** [comment]
@Shinmera Sorry for the delay. This is the tail of the log you requested:

> [pid 26673] open("/etc/passwd", O_RDONLY|O_CLOEXEC) = 16
> [pid 26673] open("/etc/default/nss", O_RDONLY|O_CLOEXEC) = 17
> [pid 26673] open("/home/alexis/Downloads/portacle//lin/lib/libnss_systemd.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> [pid 26673] open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 17
> [pid 26673] open("/lib/x86_64-linux-gnu/libnss_systemd.so.2", O_RDONLY|O_COEXEC) = 17
> Inconsistency detected by ld.so: dl-open.c: 689: _dl_open: Assertion `_dl_debug_initialize (0, args.nsid)->r_state == RT_CONSISTENT' failed!
> [pid 26684] +++ exited with 127 +++

**Comment by Shinmera** [comment]
Wait, why do you not have the libnss_systemd.so.2 file? That should be in the latest package.

**Comment by CactoBoy** [comment]
@Shinmera Tested with the latest package (1.3), but there's no libnss_systemd.so.2 in the lin/lib dir.

**Comment by Shinmera** [comment]
Are there other libnss_ files there? Copy one of those and name it libnss_systemd.so.2

**Comment by phoe** [comment]
There are:

```
┌─[phoe][phoetower][~/Downloads/portacle/lin/lib]
└─▪ ls | grep nss
libnss_compat.so
libnss_compat.so.2
libnss_dns.so
libnss_dns.so.2
libnss_files.so
libnss_files.so.2
libnss_hesiod.so
libnss_hesiod.so.2
libnss_mdns4_minimal.so.2
libnss_mdns4.so.2
libnss_mdns6_minimal.so.2
libnss_mdns6.so.2
libnss_mdns_minimal.so.2
libnss_mdns.so.2
libnss_myhostname.so.2
libnss_mymachines.so.2
libnss_nisplus.so
libnss_nisplus.so.2
libnss_nis.so
libnss_nis.so.2
libnss_resolve.so.2
```

Your workaround seems to work, at least on my machine.

**Comment by Shinmera** [comment]
They're all (almost) same file anyway.

**Comment by Shinmera** [comment]
Looks like portacle/launcher@2bc7ab95547268ed35e0e3816a0bfd147ccee0f7 is not in the release, then? Guess I should just make a new package then.

**Comment by CactoBoy** [comment]
@Shinmera Same as @phoe here. Working fine with the workaround. Thanks to both of you! You can close the issue if you don't need it to track something.
