### ISSUE TITLE
Mac OS X Portacle 1.3b has bad load-path

### ISSUE THREAD

**Issue by maueroats** [portacle/portacle#122]
Out of box installation (first run) of the Mac OS X version 1.3b fails with the following message (line break added for readability):

```
cl-struct-define: Autoloading file [...]/portacle/mac/emacs/share/emacs/25.2/lisp/emacs-lisp/
cl-lib.elc failed to define function cl-old-struct-compat-mode
```

Notice that the emacs version is `26.1`, but for some reason the load path contains `25.2`.

Probable cause: error in build process.

Workaround until really fixed: add the code below to the `portacle/config/site-start.el` file. I put mine right after the line with the comment `Set up necessary paths`.

```
(defun amo-fixit (s)
  (replace-regexp-in-string "25\\.2" emacs-version s nil 'literal))
(message "editing load-path to change 25.2 to emacs-version")
(setq load-path (mapcar #'amo-fixit load-path))
```

**Comment by Shinmera** [comment]
Can confirm. The launcher picks the wrong version, since it just sets up the load paths based on the first directory it finds in the directory listing.

**Comment by Shinmera** [comment]
Please check whether the issue persists with [1.4](https://github.com/portacle/portacle/releases/tag/1.4)
