### ISSUE TITLE
gui failure on osx 10.14.6

### ISSUE THREAD

**Issue by vrx** [portacle/portacle#126]
I have successfully compiled Portacle on 10.14.6 with brew, following recommandations in 
https://github.com/portacle/portacle/tree/master/build

But when i start it in a terminal ./mac/bin/portacle , GUI appears (window and menus) but no text, no interaction. 

Please note that i can launch Portacle.app from the binary releases from here https://portacle.github.io/#get-mac

**Comment by Shinmera** [comment]
I believe emacs has problems being launched from the command line. Try running the Portacle app instead. I don't know why that emacs problem exists, but it's not Portacle's fault.

**Comment by vrx** [comment]
thanks for your reply, but unfortunately i get the same result when launching the resulting packaged Portacle app. could it be linked to my osx version ? i understood that for some security reasons, we had to move back and forth the Portacle.app file before being able to open it but in that case this does not change anything. really seems to be blocked with textual display.

**Comment by Shinmera** [comment]
I have no clue, sorry.

**Comment by vrx** [comment]
./mac/bin/emacs -nw  works fine

wonder if it is related to this
http://emacs.1067599.n8.nabble.com/bug-31904-27-0-50-Emacs-doesn-t-render-text-modeline-Mac-OSX-10-14-Mojave-td458613.html

**Comment by vrx** [comment]
in emacs.sh
readonly TAG=emacs-26.3
fixed it :-)
