### ISSUE TITLE
Default Font Size Does NOT "Stick"

### ISSUE THREAD

**Issue by haziz** [portacle/portacle#128]
I have repeatedly set the default font, and to the best of my knowledge saved my choice but it just does not stick. I looked in the .../portacle/config/user.el file and do find this:

    (custom-set-faces
     ;; custom-set-faces was added by Custom.
     ;; If you edit it by hand, you could mess it up, so be careful.
     ;; Your init file should contain only one such instance.
     ;; If there is more than one, they won't work right.
     '(default ((t (:background nil :family "Noto Sans" :foundry "monotype" :slant normal :weight normal :height 120 :width normal)))))

Despite this reopening Portacle still gives me an excessively small font.

Thanks.

**Comment by Shinmera** [comment]
https://github.com/portacle/portacle/issues/41#issuecomment-411131078

**Comment by haziz** [comment]
Can you elaborate a bit further, and keep in mind that I am not an Emacs or Emacs Lisp guru. I did try M-x portacle update and still cannot get it to save.

Adding:

    (add-to-list 'default-frame-alist '(font . "-GOOG-Noto Mono-normal-normal-normal-*-14-*-*-*-m-0-iso10646-1"))

to user.el also does not fix the issue.
