### ISSUE TITLE
Remove tutorial

### ISSUE THREAD

**Issue by phoe** [portacle/portacle#130]
The default emacs tutorial is confusing, since it refers to keybindings that are modified (for example, `M-x` being bound to `execute-extended-command`). One newcomer to Lisp has fallen in that hole today.

I suggest replacing the whole tutorial file with something that in the very least is not confusing to newcomers (e.g. an empty file, or a file linking to `#lisp` and `#clschool` on Freenode or the Lisp Discord server).

**Comment by Shinmera** [comment]
I think a good option would be to make whatever opens the tutorial open the portacle help buffer instead

**Comment by phoe** [comment]
Seems like the elisp function `help-with-tutorial` should be redefined.

https://github.com/emacs-mirror/emacs/blob/d0e2a341dd9a9a365fd311748df024ecb25b70ec/lisp/tutorial.el#L736
