### ISSUE TITLE
Emacs UI trashes Ubuntu MATE 18.04

### ISSUE THREAD

**Issue by robert-pearson** [portacle/portacle#134]
I am running Ubuntu MATE 18.04. I installed Emacs and tried to get through the tutorial. The Emacs UI is not a GUI and corrupts the Ubuntu keyboard handler so that the keyboard does not work properly for any program. Re-booting is not enough. I needed to do a cold re-boot before my keyboard would work properly.  Does portacle Emacs use the 35-year old curses UI or a modern GUI which will not screw up my keyboard?  My hardware is AMD x86 64-bit.

If portacle uses Emacs with the obsolete destructive curses UI, I need to know so that I can avoid your product.

**Comment by Shinmera** [comment]
Emacs can run as a GTK+ application or in a terminal. As shown on the Portacle website, the intended way to use it is with the GTK+ frontend.

In any case, this is not the right place to report issues with your distribution.
