### ISSUE TITLE
Strange warnings on OS X

### ISSUE THREAD

**Issue by Trebor-Huang** [portacle/portacle#138]
By directly executing the `portacle` executable in the application, the console outputs the following warnings:
```
Warning: arch-dependent data dir '/Users/linus/portacle/mac/emacs/libexec/emacs/26.3/x86_64-apple-darwin15.6.0/': No such file or directory
Warning: Lisp directory '/Users/linus/portacle/mac/emacs/share/emacs/26.3/lisp': No such file or directory
```
Why should `linus` be in my `Users` folder? This does not affect my usage in any way. But if `linus` were really an existing user, and he had emacs installed, would it start off the wrong emacs? I haven't got the time to test this.

**Comment by Shinmera** [comment]
Duplicate #137
