### ISSUE TITLE
Addition of Portacle to PortableApps.com!

### ISSUE THREAD

**Issue by Peppernrino** [portacle/portacle#140]
I have packaged Portacle in .paf.exe format for PortableApps.com, and would like to finally inform you!

https://portableapps.com/node/63177

Let me know what you think. If there are no bugs, etc, we can put it on the list to be added to the official list of apps. :)

**Comment by Shinmera** [comment]
Neat! I don't have time to maintain an external source, but if you'd like to, I'd be fine with that.
