### ISSUE TITLE
Question/Improvement - A few shortcuts missing

### ISSUE THREAD

**Issue by tadas-subonis** [portacle/portacle#142]
I would like to be able to:
 

1. When I am in a scratch buffer after I write a function/line/expression, I would like to have a shortcut to execute it immediately in REPL. Something like C-c C-k
2. When I am in slime-repl buffer, I would like to be able to send the last command to the bottom of the scratch buffer.
3. EDIT: I would like to be able to execute an entire block/cell of LISP code. For example, everything between `# %%` `# %%` like it works inside Julia/Python in a console mode.

Is there any way to do that now? I am a complete newbie with Emacs so I might be missing something obvious.

**Comment by hajovonta** [comment]
Hi @tadas-subonis for the first question you can press C-M-x which will evaluate your expression at point. For the second, I usually just copy-paste the expression.

**Comment by tadas-subonis** [comment]
Also, is there a shortcut to display documentation of the current function?

At the moment, I am using `M-.` to jump to the definition and read the doc there.

**Comment by Shinmera** [comment]
When typing out a function you can pause for a bit which should open the company candidates list, including documentation for the currently selected candidate. You can also run the function `slime-documentation` to get the docstring for the definition at point. If you need that frequently you could add a shortcut for it in `user.el`.
