### ISSUE TITLE
Command line launch

### ISSUE THREAD

**Issue by Gallowglass77** [portacle/portacle#143]
How do I launch from the command line? Total noob. Could not find Shirakumo on freenode. Installed to linux(beta) on a chromebook so CL only.

**Comment by Shinmera** [comment]
`./portacle.run` ought to do it.

**Comment by Gallowglass77** [comment]
Thank you. The ./ did it. Why did portacle.run from withing the portacle directory not do it?

**Comment by Shinmera** [comment]
That's just how the linux shell works.
