### ISSUE TITLE
Is there a way to reset the REPL?

### ISSUE THREAD

**Issue by MrYossu** [portacle/portacle#146]
Sorry if this is a dumb question, or if it isn't a Portacle-specific one.

Suppose I'm doing stuff in the REPL, testing functions, setting variables, etc, and then want to reset the REPL so I'm back where I started, or even switch to another project without the old stuff hanging around.

Other than closing Portacle and restarting, is there a way to reset the REPL back to its pristine state? I tried closing the REPL buffer, but then couldn't find a way to open it again (or open a new one), and had to restart Portacle.

Anyone able to help? Thanks.

**Comment by Shinmera** [comment]
In the repl type `,restart` as mentioned in the [help buffer](https://github.com/portacle/config/blob/master/help.txt#L242-L243)

**Comment by MrYossu** [comment]
@Shinmera Thanks. Looks like I need to read that doc more closely!

**Comment by MrYossu** [comment]
@Shinmera Actually, can I see this from within Portacle? If I look at the buffers, the only help one I see is `*portacle-help*, which doesn't contain all that info.

**Comment by Shinmera** [comment]
Hmm. Might be that that info was added since the last release then.

**Comment by Shinmera** [comment]
You can copy the contents from the linked file and put them into `portacle/config/help.txt`. The help buffer gets its contents from there.

**Comment by MrYossu** [comment]
@Shinmera Thanks.
