### ISSUE TITLE
Portacle Build on Ubuntu 20.04LTS

### ISSUE THREAD

**Issue by EarwainBanadar** [portacle/portacle#148]
Hello all,

the default build of portacle is failing due to autdated busybox.
As well the default build fails while trying to use SBCL 2.1.5

For a successful build I did two fast fixes/modifications in:

busybox.sh:
### readonly TAG=1_25_1
readonly TAG=1_33_1
-> busybox will compile w/o complaning to fail not willing to link statically to glibc

sbcl.sh
readonly TAG=sbcl-2.1.5
-> the finally compilation of sbcl will not conclude properly by two failing test of contributed modules
-> I downloaded the sbcl source directly an placed it into the build/sbcl subdirectory and did a direct build of sbcl in this directory commencing the build successfully

After that I tried build.sh again wich commenced successfully now.

These are of course ugly fixes ....

**Comment by AkashaP** [comment]
thanks for the tip about sbcl, i was having the same problem

i personally had trouble getting ag compiling too, ag hasn't had a release tag set in ages, easiest way to get that working was to fork it, push a tag, then change url in ag.sh

**Comment by ychakiris** [comment]
You might want to look at my comments on another issue: https://github.com/portacle/portacle/issues/141#issuecomment-766597404. I had to change the build in order to build from source.

**Comment by Shinmera** [comment]
Fwiw I've also observed SBCL test failures on older Linuxes. Not really anything to do with Portacle, I'm afraid. However, even if the tests fail, the build should still be fine. You can skip over a step by adding it to `.portacle-finished-fragments`.
