### ISSUE TITLE
Increase Heap

### ISSUE THREAD

**Issue by Woodi-dev** [portacle/portacle#151]
Hey there,
I am new to Portacle and I wanna increase the heap size.
As far as I know, this is possible by calling sbcl --dynamic-space-size. How do I set up this in Portacle on Windows?

Thanks in advance

**Comment by fduhia** [comment]
Hi,
I managed to set the --dynamic-space-size option in the portacle-slime.el file. You can find it inside the main portacle directory "all\emacsd\portacle\portacle-slime.el".
Change line 43 as referenced here [portacle-slime.el](https://github.com/portacle/portacle/issues/99#issuecomment-478974250) like so: 
```
(setq slime-lisp-implementations
      `((sbcl (,(portacle-bin-path "sbcl") "--dynamic-space-size" "1024"))))
```

Best Regards
