### ISSUE TITLE
Cannot execute portacle.app on OS X Big Sur 11.5

### ISSUE THREAD

**Issue by nigelvictorrees** [portacle/portacle#152]
It's blocked with 'cannot be opened because the developer cannot be verified'.
I have attempted these remedies:

- Moved _portacle.app_ into projects and back. 

- Applied sys _preferences_ to be able to Open it.

- Applied _curl -L https://github.com/portacle/portacle/releases/download/1.4/mac-portacle.dmg --output mac-portacle.dmg_

Seems to start but then hits 'cannot be opened ...' for some other object such as _libgnutls.30.dylib_ and dumps a report.

**Comment by metayan** [comment]
Wild guess: What if you try setting "Full Disk Access" for Portacle in the Privacy settings in System Preferences?

The report might be helpful.

**Comment by nigelvictorrees** [comment]
Thank you. I just tried that. Alas; double-clicking on the app gave a failure re library not loaded… library load disallowed by system policy. The object referenced is libgnutls.30.dylib. I attach a screenshot of the Problem Report.

I suspect I’ve missed some simple step.  

I’m going to Bin the folders etc re Portacle and download it afresh, just to make sure my attempts haven’t tinkered with some necessary structure. I’ll then do the Full Disk Access again.

Thanks for your help.

**Comment by chespinoza** [comment]
Same, also using Big sur.
I tried though running the portacle script inside the portacle app and got this that could be hint of the issue:
```
“emacs-26.3” cannot be opened because the developer cannot be verified.
```

**Comment by Shinmera** [comment]
Hi. Please try the latest pre-release: https://github.com/portacle/portacle/releases/tag/1.4c
It was created under macOS 12, so it may not launch on older versions. I'd be interested to know about that.
It's been signed using a self-signed certificate, which must first be installed using the mac-fixup.sh script. The script will also clear security attributes. Unfortunately there's no way to make the script runnable via a simple double-click, so it has to be done via the terminal.

Closing this, as all mac problems are pretty much the same atm. Please continue discussions in https://github.com/portacle/portacle/issues/127
