### ISSUE TITLE
Quicklisp can't find binaries(is this the right term?)

### ISSUE THREAD

**Issue by piera8** [portacle/portacle#163]
Using Portacle on windows 10.  
I have been attempting to load a few libraries through quicklisp such as gsll(gnu scientific library for lisp) and others, but tend to fall into the debugger, with errors such as:

Error while trying to load definition for system gsll from
pathname
c:/Users/me/portacle/all/quicklisp/dists/quicklisp/software/gsll-quicklisp-eeeda841-git/gsll.asd:

   Couldn't execute "gcc": The system cannot find the file specified.
   [Condition of type ASDF/FIND-SYSTEM:LOAD-SYSTEM-DEFINITION-ERROR]

I am not great with portacle and how it looks for things, being portable and all.. Is there an easy fix for this? Do I need to download some .dlls and place them somewhere in the portacle folder? etc..

 I have had problems like this in the past and usually bypass these by selecting a debugger option to "continue as if compilation did not fail". Never had issues afterward, but this can't be good practice.

**Comment by piera8** [comment]
Wow, quick response. Thank you! I'll update this thread once I find more info.

**Comment by Shinmera** [comment]
Sure. Good luck!
