### ISSUE TITLE
Font settings not saving

### ISSUE THREAD

**Issue by TheMrAmazing** [portacle/portacle#166]
Hi I am using a high dpi screen, and so the default text size is virtually unreadable. I have used the Options > Set Default Font as well as saved the settings several times. I've also tried customize the default face, none of it will stick, on restart I am back to the small font size. What do I need to do?

**Comment by Shinmera** [comment]
Duplicate of #128

**Comment by TheMrAmazing** [comment]
Perhaps, it is a duplicate, but it is not actually fixed, and his solutions of changing the value to 22 didn't actually work for me
