### ISSUE TITLE
[Windows] Hide startup terminal

### ISSUE THREAD

**Issue by sohang3112** [portacle/portacle#169]
I just installed Portacle using [the official Windows instructions on homepage](https://portacle.github.io/#get-win).
When I open Portacle, the main Emacs GUI and an an empty terminal window opens. 
Is there a way to get rid of this unnecessary terminal window?

**OS:** Windows 11

**Comment by Shinmera** [comment]
It is, unfortunately, not "unnecessary". The terminal window should close on its own pretty quickly, anyway.

**Comment by sohang3112** [comment]
> The terminal window should close on its own pretty quickly, anyway.

@Shinmera That's the point - it *doesn't* close automatically. The terminal stays open as long as the Emacs window is open.

**Comment by norman-kraft** [comment]
I have the same problem under Windows 11, the terminal stays open until I close Emacs.

**Comment by Shynur** [comment]
good news is that the Emacs process doesn't terminate even when the terminal window is closed

**Comment by sohang3112** [comment]
@shynur In my case, Emacs *does* terminate when I close the terminal window. Also, the terminal window started by Emacs shows the following warning message (I don't know if it's important or not):
```
(process:7520): GLib-GIO-WARNING **: 11:20:12.845: Unexpectedly, UWP app `HaukeGtze.NotepadEditor_1.8420.1.0_x64__6bk20wvc8rfx2' (AUMId `HaukeGtze.NotepadEditor_6bk20wvc8rfx2!notepad') supports 182 extensions but has no verbs
```
