### ISSUE TITLE
*compile-file-truename* and  *compile-file-pathname* stay NIL

### ISSUE THREAD

**Issue by AnalogFile** [portacle/portacle#177]
Using Portacle on a MacBook Pro (13-inch, M1, 2020) macOS Monterey 12.7.6 (21H1320)

Just checked multiple dynamic variables adding in a file:

(defparameter *my-default-pathname-defaults* *default-pathname-defaults*)
(defparameter *my-load-truename* *load-truename*)
(defparameter *my-load-pathname* *load-pathname*)
(defparameter *my-compile-file-truename* *compile-file-truename*)
(defparameter *my-compile-file-pathname* *compile-file-pathname*)

Makes easy to compile that file then load it and then check at CL-USER using the *slime-repl cbcl* buffer. Results are:

*default-...* is there (of course!)

*load-...* are both set to a *.fasl path (even if I call compile-file directly from the slime-repl buffer without :output-file) 

*compile-file-...* are both NIL and this is wrong! 

Just read www.cs.cmu.edu/Groups/AI/html/cltl/clm/node224.html#SECTION002910000000000000000

It's long but I'll copy here the related  parts of the text of the standard:
25.1. The Compiler
....
....
X3J13 voted in June 1989 (LOAD-TRUENAME)   to require that compile-file bind two new variables *compile-file-pathname* and *compile-file-truename*; the dynamic extent of the bindings should encompass all of the file-compiling activity.
....
[Variable]
*compile-file-pathname*

X3J13 voted in June 1989 (LOAD-TRUENAME)   to introduce *compile-file-pathname*; it is initially nil but compile-file binds it to a pathname that represents the file name given as the first argument to compile-file merged with the defaults (see merge-pathname).

[Variable]
*compile-file-truename*

X3J13 voted in June 1989 (LOAD-TRUENAME)   to introduce *compile-file-truename*; it is initially nil but compile-file binds it to the ``true name'' of the pathname of the file being compiled. See truename.
....
....

**Comment by Shinmera** [comment]
your defparameter value is not evaluated at compile time, but at load time, at which point compile-file-pathname is nil

the behaviour is correct, your assessment is wrong.

and even if it weren't this has nothing to do with portacle.

**Comment by vindarel** [comment]
@AnalogFile Let's chat on reddit or Discord if you want more help.

https://www.reddit.com/r/learnlisp

https://discord.gg/hhk46CE

**Comment by AnalogFile** [comment]
You are right!

Damn. 
I forgot eval-when.
