### ISSUE TITLE
MacOS options do not persist after closing the app.

### ISSUE THREAD

**Issue by ryn1x** [portacle/portacle#41]
MacOS options do not persist after closing the app. (i.e. changing the theme or font size)

**Comment by Shinmera** [comment]
I don't understand how theme or font size are "Mac OS options". If you are talking about the Emacs commands to change its theme or frame font, then that's just how Emacs works. If you want to persist a change, put it into the `config/user.el` file as instructed by the help buffer.

**Comment by WhiskyRyan** [comment]
I think it may be the way emacs is bundled into the portacle.app on macOS. I have no problems with standard emacs. If I change and save any settings from the tool bar or from the customize emacs "gui" they do not persist. I did have success changing my font and theme by modifying the bundled emacs-init.el though...

**Comment by ptrckqnln** [comment]
Unfortunately I'm having this issue with the latest version.

**Comment by pawel-dubiel** [comment]
I have the same problem. Saving theme or font through the GUI on MacOS doesn't work. ( user.el is not modified )

Interesting is that when I use M-x customize-face 
the new settings are saved to user.el but on the restart still can't see new settings.

**Comment by joebentley** [comment]
I'm having the same issue, I have to manually run the custom-set-faces command from user.el for the change to take place

**Comment by Shinmera** [comment]
The font thingy is due to the way Portacle sets its own font and the way emacs' customisations take precedence. If you use something like

    (add-to-list 'default-frame-alist '(font . "Noto Mono-10:antialias=subpixel"))

in your `user.el` it should work as expected.

**Comment by Shinmera** [comment]
Actually now that I look at the code I think I see the problem. Portacle's default window customisations are applied after the user file is loaded. This was changed in some relatively recent patch, I think.

**Comment by pawel-dubiel** [comment]
I am new to emacs and I had a problem to make this work,  but finally, it works for me.

- applied Shinmera path https://github.com/portacle/emacsd/commit/b21ec3af9fa69b45e8eb87d85f58308b21f2586f 
- `(add-to-list 'default-frame-alist '(font . "Noto Mono-13:antialias=subpixel"))` in user.el
- remove portacle-user.elc and remove portacle.elc 
- then open portacle and recompile everything with`C-u 0 M-x byte-recompile-directory`

It could be that one of these steps wasn't required, but now it works for me.

**Comment by Shinmera** [comment]
Instead of manually applying the patch, removing the elcs, and byte-recompiling, you could've also just done `M-x portacle-update`

**Comment by pawel-dubiel** [comment]
@Shinmera Thanks, that's really good trick :) I'should have scanned for such commands first.
