### ISSUE TITLE
Suggestions for OSX Portacle

### ISSUE THREAD

**Issue by mcheema** [portacle/portacle#45]
First, this is a really commendable project and I hope it would encourage people to try common lisp.  I know I can now ask my son to try out common lisp one he's done with SICP/racket.

I installed it today on a fresh macbook air (2015) and the instructions worked great.  I was looking through the help page and noticed C-left C-right and C-up, C-down for slurping/barfing/convoluting.  These are trapped by OSX but the C-{} C-() M-up down bindings work.

Also, maybe a suggestion somewhere to OSX users that they might find making command key Meta, in Emacs, more ergonomic:
`(when (eq 'darwin system-type) (setq mac-command-modifier 'meta))
`
On a similar line a suggestion to all users that they switch caps lock and control key in settings for ergonomic reasons.

**Comment by Shinmera** [comment]
The current pre-release has some OS X keybinding related changes. I think I already changed command to be meta, but it's been some months and I don't quite recall.

Thanks for your note about C-up/down/left/right! I'll see what I can do for suitable alternatives.

**Comment by mcheema** [comment]
Just to be clear c-{ c-} for barfing and c-( c-) for slurping are already bound and its just a note in the doc for OSX users to use these that's required.
