### ISSUE TITLE
MacOS High Sierra beta build.

### ISSUE THREAD

**Issue by shmuga** [portacle/portacle#47]
Just FYI it doesn't work on High Sierra (from latests release).
But I've tried to build it by myself and after that it starts working!

**Comment by Shinmera** [comment]
It's really disappointing how little Apple seems to care about backwards compatibility.

Thanks for the heads up!

**Comment by ClarenceClark** [comment]
The problem is with the quarantine; to disable, run `xattr -d com.apple.quarantine path/to/Portacle.app/`

**Comment by Shinmera** [comment]
That can be circumvented by following the [steps on the website](https://portacle.github.io/#get-mac).

**Comment by ClarenceClark** [comment]
Hmm... reproduction steps? It's running fine pre-built on my latest 10.13 beta.

**Comment by ClarenceClark** [comment]
Actually, I just tested it on my laptop running beta 9, and there is _no way_ to disable gatekeeper without `xattr`. Maybe I'm running a buggy build, but it only prompts for me to open the first time it opens, and even if I click 'open', nothing happens, and nothing shows up in the System Preferences menu under Security.

It seems like `xattr -d` is the only way to un-quarantine a file for now.

**Comment by Shinmera** [comment]
@IsaacKhor I can't replicate your observed behaviour on a fresh install of OS X 10.13. Portacle works just fine out of the box with the provided instructions for moving the .app with Finder.
