### ISSUE TITLE
Error running hunspell

### ISSUE THREAD

**Issue by mcheema** [portacle/portacle#48]
On a vanilla OSX Sierra set up with no homebrew etc there is no libintl (from gettext) in /usr/local/opt/lib. This is needed by hunspell which is used by flyspell. It's easy enough to install the library using the usual curl, make, make install routine, but if the purpose is an out of the box Dr. Racket like experience then it would be good to include that library in Portacle.

**Comment by Shinmera** [comment]
Ah hell. I thought I had taken care of that already. Thanks for the heads-up.

**Comment by Shinmera** [comment]
This should be fixed as of 492fff29ef41a0266ce9115658b806018f54ac27
