### ISSUE TITLE
Release console after start on Windows

### ISSUE THREAD

**Issue by dmitrys99** [portacle/portacle#50]
When one run portacle.exe from cmd or other console program (say, Far manager), program does not release console window until exit from Emacs, leading to unnecessary console window in task bar.

**Comment by Shinmera** [comment]
A running program that is launched from the command prompt will keep the prompt busy until it's closed. That's standard behaviour, no?

**Comment by dmitrys99** [comment]
It is usual behaviour in *nix systems. But on Windows, if you run GUI program (or which will create GUI later), console window is not being hold usually.
The behaviour I'm trying to show is similar to 
`start /B portacle.exe`

**Comment by Shinmera** [comment]
I'm not sure how much, if at all, I want to follow this. Some components depend on the exit code of sub-applications, which means they require it to block.

**Comment by dmitrys99** [comment]
I believe simple *.bat file with one line `start /B portacle.exe` would be fine
Attached bat file (rename from *.txt)
[portacle.txt](https://github.com/portacle/portacle/files/1309520/portacle.txt)
