### ISSUE TITLE
macOS - No image display, no PDF rendering.

### ISSUE THREAD

**Issue by nachoba** [portacle/portacle#52]
It seems that I cannot see neither image files nor read pdfs etc, all that appears is the "binary".
Thought it was that gs was missing in my system, but no.

I'm on High Sierra (not to be confused by I'm high on Sierra LOL) 
Thanks for any advice

**Comment by Shinmera** [comment]
Any kind of extraneous emacs functionality like image rendering and so forth is excluded from the Portacle builds to minimise dependencies. You should use your system's native applications to view these types of files.

**Comment by nachoba** [comment]
Ok, makes sense. Thanks!

**Comment by Shinmera** [comment]
A case could be made that these kinds of files should be automatically opened in the system's native application (using something like openwith-mode) but I'm undecided on that since it might also be confusing if you really do want to open a file like that in emacs as a binary or text buffer.
