### ISSUE TITLE
Portacle Does Not Launch on MacOS Sierra 10.12.1

### ISSUE THREAD

**Issue by artforlife** [portacle/portacle#53]
I wanted to check your product today as an alternative to piece-meal Emacs + SBCL + Quicklisp installation. However, I cannot get it to work on my Mac. It appears to launch but then crashes (no error, but I can see it appear briefly in the dock).

I have enabled applications by unidentified developers.

If you know how I could resolve this, please advise.

**Comment by Shinmera** [comment]
Did you move the `.app` into a separate folder and back using Finder as [instructed on the website](https://portacle.github.io/#get-mac)?

**Comment by yelluw** [comment]
For anyone running into this issue, here is how I fixed it:

1.  Open the `mac-portable.dmg` file downloaded from the [portacle website](https://portacle.github.io/)

2. Copy the files extracted. In my case, I pasted them into the `Applications` folder.

3. Select the `Portacle.app` file. Move it (drag it) to the `projects` directory. Both are in the same folder.

4. Drag the `Portacle.app` file back to where it was (outside of `projects`).

5. Double click `Portacle.app` and it should work.

**Comment by Shinmera** [comment]
Closing this due to lack of feedback and most likely user error.

**Comment by xiaoxiaowesley** [comment]
> For anyone running into this issue, here is how I fixed it:
> 
> 1. Open the `mac-portable.dmg` file downloaded from the [portacle website](https://portacle.github.io/)
> 2. Copy the files extracted. In my case, I pasted them into the `Applications` folder.
> 3. Select the `Portacle.app` file. Move it (drag it) to the `projects` directory. Both are in the same folder.
> 
> <img alt="screen shot 2018-03-15 at 1 05 09 pm" width="211" src="https://user-images.githubusercontent.com/23017027/37478793-8ea38094-2851-11e8-9ca7-11626e9505cd.png">
> 
> <img alt="screen shot 2018-03-15 at 1 05 54 pm" width="378" src="https://user-images.githubusercontent.com/23017027/37478835-a0bf84b2-2851-11e8-87c5-b49c526cf542.png">
> 
> 1. Drag the `Portacle.app` file back to where it was (outside of `projects`).
> 
> <img alt="screen shot 2018-03-15 at 1 06 25 pm" width="392" src="https://user-images.githubusercontent.com/23017027/37478910-b4aff196-2851-11e8-850b-df99616f9ba0.png">
> 
> 1. Double click `Portacle.app` and it should work.

I works! But why?

**Comment by Shinmera** [comment]
Because Apple implemented really weird application behaviour for what they claim to be security reasons. Basically, an application downloaded from the net has a special bit set that causes it to be executed in a random directory when launched. Portacle requires its surrounding environment to work, so that breaks the application. Moving it with Finder causes that bit to get unset, and it will then be exectued where it is, as it should be.

I don't understand why this restriction is supposed to help at all with anything, but it is definitely a pain in the ass.

**Comment by mathyingzhou** [comment]
@yelluw Thankfully your approach works. I'm on macOS 10.13.

**Comment by noname007** [comment]
I'm on macOS  10.14.5

**Comment by jonfast565** [comment]
Can confirm that @yelluw 's answer works on macOS 10.14.6 as well.

**Comment by sefaenesergin** [comment]
is that working on macOS 10.15.4

**Comment by pryelluw** [comment]
@sefaenesergin I just tested to answer your question and it worked. Please give it a try and reply if you encounter any issues.

**Comment by m01ar** [comment]
macOS Big Sur 11.3.1
Only this way helped me:
`~ $ curl -L https://github.com/portacle/portacle/releases/download/1.4/mac-portacle.dmg --output mac-portacle.dmg`

**Comment by M-a-k-l-o-v** [comment]
<img width="998" alt="Screenshot 2021-11-16 at 7 16 34 PM" src="https://user-images.githubusercontent.com/89027053/142012384-484de0cb-6eae-46ce-abd0-5d2181e143d0.png">
 it doesn't work for mine

**Comment by M-a-k-l-o-v** [comment]
@pryelluw

**Comment by pryelluw** [comment]
@M-a-k-l-o-v 

I've confirmed the issue you are having.

The work around I had posted before no longer works.

The only thing that seems to work is:

Run

`~ $ curl -L https://github.com/portacle/portacle/releases/download/1.4/mac-portacle.dmg --output mac-portacle.dmg`

Open the installer.
Click on portacle


I cannot get it to run if I move the application to the Applications folder.

**The errors OSX 11.6 is showing is that some of the libraries portacle depends on are being blocked from loading.**

**Comment by p0w1nd** [comment]
> macOS Big Sur 11.3.1 Only this way helped me: `~ $ curl -L https://github.com/portacle/portacle/releases/download/1.4/mac-portacle.dmg --output mac-portacle.dmg`

Thanks! This works for me. I'm on macOS 12.4 (Monterey).To be precise: after that curl command, I click on the .dmg file and copy the portacle folder to a local location - not running portacle directly inside the virtual drive.

**Comment by AidenDrake** [comment]
For me running the command:
```sudo  xattr  -r  -d  com.apple.quarantine  . ```
In my portacle folder got rid of the popup saying that "Apple can not verify this software is not malware." Which I got quite a few times for different applications in the folder.

Source of the command: https://marcus3santos.github.io/lisp-ide.html
