### ISSUE TITLE
Hyperspec lookup doesn't work

### ISSUE THREAD

**Issue by simonbagley** [portacle/portacle#54]
When I click  on the menu item:
SLIME-->Documentation-->Hyperspec...
and enter the text "loop", I get the following error message:
"Searching for program: No such file or directory, xdg-open

I am running portacle on a Windows 10 64 bit PC, with a recent version of mingw/msys installed.
Any idea how to fix this error?

**Comment by Shinmera** [comment]
Not off the top of my head. Probably related to how Emacs opens the browser being configured for Linux rather than Windows.

**Comment by simonbagley** [comment]
You're right. Thanks for pointing me to the right place.
I have fixed it by customizing the emacs Browse Url Browser Function to use the default windows browser.

**Comment by Shinmera** [comment]
Fixed.
