### ISSUE TITLE
Not working on windows 7

### ISSUE THREAD

**Issue by unuunc** [portacle/portacle#55]
Steps -
1. run installer and gave path to D:\poratcle
2. From installed folder executed portacle.exe

A window comes but nothing after that (no error thrown)

**Comment by unuunc** [comment]
on the same machine pre-release version works fine (checked after trying released version)

**Comment by Shinmera** [comment]
I've heard reports of it taking just a really long time to start up the first time (for reasons beyond me).

**Comment by Shinmera** [comment]
This is the same as #58, closing
