### ISSUE TITLE
Emacs is getting very slow while editing lisp files.

### ISSUE THREAD

**Issue by MartinBuchmann** [portacle/portacle#56]
I have installed Portacle on my Laptop under Win10 and everything works fine but when I am editing a lisp file it is getting extremly slow. It takes several seconds to respond to keystrokes. In the repl it is faster but even simple commands like switchign buffers lead to a short delay.

I have deactivated semantic parsing and flyspell without any change. I could not spot the issues further. Is this phenomena know already? Anything I could do?

**Comment by Shinmera** [comment]
It might be related to company mode eating your resources. Try disabling that.

**Comment by MartinBuchmann** [comment]
I comment out the corresponding line in portacle.el without any change.

**Comment by Shinmera** [comment]
Disabling that line might not be enough. However, you can easily check whether company is active by the mode line.

**Comment by MartinBuchmann** [comment]
Hmm, I disabled company but this did not solve my problem. If I use a fresh and single lisp file, it looks good. But if I am editing a file (50 lines only) which is part of a larger system (it's own package and asdf file with 60 files) it slows down drastically. Is there some parsing in the background which could get a hick-up?

**Comment by Shinmera** [comment]
The configuration Portacle is using isn't doing anything unusual or specific about that that I'm aware of. I've never had it pause that badly before with such small files.

**Comment by MartinBuchmann** [comment]
Unfortunately I was not able to investigate this further. I know too little about Win10. I installed vanilla Emacs and sbcl directly and was able to get my basic configuration running. I think you could close this issue for now, maybe it is something special about my system I do not understand.

**Comment by Shinmera** [comment]
Well, I'm sorry you couldn't get Portacle to run properly. I wish I had any idea how to tackle the problem.
