### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by sanket12345** [portacle/portacle#58]
The portacle.exe does'nt open the GUI editor. It only opens up command prompt interface.

**Comment by Shinmera** [comment]
See #55. How long did you wait after the command prompt opened? Sometimes it can take a long time for it to show up, for no discernible reason.

**Comment by sanket12345** [comment]
I waited for 2-3 minutes approximately.

**Comment by Shinmera** [comment]
Hm. Can you run the following from a command prompt in the portacle directory?
```
set PORTACLE_DEBUG=1
portacle.exe
```
Do you notice any CPU usage at all? The launcher should just prepare some environment variables and then run the emacs executable, so I really don't understand why it might get stuck on anything.

**Comment by sanket12345** [comment]
Yes i ran the command using the prompt.
Following is the screenshot of the result:
But I am getting the same result. Launcher is still stuck.

**Comment by Shinmera** [comment]
Github does not relay email attachments.

**Comment by sanket12345** [comment]
Oh okay
Following are the contents of the attachment
C:\Users\Hp\portacle>
C:\Users\Hp\portacle>set PORTACLE_DEBUG=1

C:\Users\Hp\portacle>portacle.exe
  Portacle Launcher System Info:
App:           emacs
Platform:      win
Root:          C:\Users\Hp\portacle\
Binary Path:
 C:\Users\Hp\portacle\\win\lib\;C:\Users\Hp\portacle\\win\bin\;C:\windows\system32;C:\Python27;C:\MinGW\bin;C:\Program
Files (x86)\Git\cmd;C:\adb;C:\Program Files
(x86)\Brackets\command;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Excersism;C:\Program
Files
(x86)\Google\Chrome\Application;C:\windows\system32;C:\Python27;C:\MinGW\bin;C:\Program
Files (x86)\Git\cmd;C:\adb;C:\Program Files
(x86)\Brackets\command;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\windows\system32;C:\Python27;C:\MinGW\bin;C:\Users\Hp\AppData\Local\Microsoft\WindowsApps;C:\Exercism;C:\Apache2\bin;C:\Users\Hp\portacle;C:\Users\Hp\portacle\portacle.exe;
Library Path:
C:\Users\Hp\portacle\\win\lib\;C:\Users\Hp\portacle\\win\bin\;C:\windows\system32;C:\Python27;C:\MinGW\bin;C:\Program
Files (x86)\Git\cmd;C:\adb;C:\Program Files
(x86)\Brackets\command;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Excersism;C:\Program
Files
(x86)\Google\Chrome\Application;C:\windows\system32;C:\Python27;C:\MinGW\bin;C:\Program
Files (x86)\Git\cmd;C:\adb;C:\Program Files
(x86)\Brackets\command;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\windows\system32;C:\Python27;C:\MinGW\bin;C:\Users\Hp\AppData\Local\Microsoft\WindowsApps;C:\Exercism;C:\Apache2\bin;C:\Users\Hp\portacle;C:\Users\Hp\portacle\portacle.exe;

**Comment by JaumeGreen** [comment]
I had the same issue, but ultimatelly it worked.

First I installed in "d:\dev", and it didn't work. I deleted everything, restarted the computer and reinstalled in "d:\dev\" and it worked, not sure what made it work.

I'm open to do some tests if you like.

**Comment by Shinmera** [comment]
Huh, that's interesting and only makes it all the weirder.

All I can gather so far is that somehow, for some reason, the launcher can get stuck somewhere in this region of code: https://github.com/portacle/launcher/blob/master/src/portacle.c#L25-L97 https://github.com/portacle/launcher/blob/master/src/portacle_win.c#L66-L79

Nothing really springs to mind as to why that might happen or how, especially since it just sometimes mysteriously can begin to work.

**Comment by stephensmith9** [comment]
Just installed on my Windows 10 box with no issues at all. Installed to D:\<myusername>\

Windows 10 Home, Version 1709, OS Build 16299.192 (I have installed the Fall Creators Update FWIW)

This probably won't help solve the problem (sorry) but at least it's proof that it does work on Windows 10 for some of us.

**Comment by franissirkovic** [comment]
Hi. I have encountered the problem. I have renamed fonts dir (<root>\all\fints) just to skip handling of fonts. I can start portacle now. Also, I have noticed the problem on company windows. I have no problem on my personal PC.

**Comment by ntrocado** [comment]
FWIW, I had the same problem, deleted the fonts directory and it works now.

**Comment by logicking** [comment]
Have the similar problems on both my computers (Windows 10 Home and Pro)
Just an empty window.

![image](https://user-images.githubusercontent.com/265684/42424066-e6b5e116-830d-11e8-9ee6-c06e1756f6d0.png)

**Comment by jkabrg** [comment]
I tried fixing it by deleting the fonts, but it hasn't worked for me. It opens up a blank terminal window.

**Comment by Shinmera** [comment]
I won't be able to help with this unless someone can use a debugger to interrupt the process and get a trace from it.

**Comment by jkabrg** [comment]
What happens if we've already got `git` and the basic GNU utils installed on our computers? Is it possible to disable them one by one?

**Comment by Shinmera** [comment]
They're not touched by the emacs startup sequence so it makes no difference.

**Comment by jkabrg** [comment]
Sorry, I deleted the comment above.

BTW, I made a copy of the program (and its entire directory), deleted the fonts dir, and started it. It works now.

**Comment by Shinmera** [comment]
So much for that. Other people have reported that simply moving the directory elsewhere made things work. I really don't know what this is about.

**Comment by roumor** [comment]
I have the same problem on windows 8. Tried renaming the fonts folder but it didn't help

**Comment by Shinmera** [comment]
With portacle/launcher@8d8ac297db89cd70d2c0fd903c8ddc377fdf8f11 this should hopefully finally be fixed now. I'll prepare a hotfix in a moment for everyone to test.

**Comment by Shinmera** [comment]
Sorry for the delay, here it is: https://github.com/portacle/portacle/releases/tag/1.2c

**Comment by znahman** [comment]
@Shinmera FYI - I just downloaded and had the same problem. Copying and pasting the installed directory did not work. I restarted my computer and reinstalled to D:\lisp\ (making sure to specify the second '\') and now it's working.

**Comment by znahman** [comment]
> Did you try 1.2c or what?

I just checked. I actually had 1.2b.

Downloaded 1.2c and it works without copying the directory anywhere. 

FYI - the "latest release" link on the https://portacle.github.io/ page still links to 1.2b (that's why I originally had the older version)

Thank you!

**Comment by Shinmera** [comment]
I hadn't pushed the link to the website because I was still waiting for a confirmation from here. Now that I have it I can do that. Thanks!
