### ISSUE TITLE
Emacs prohibits character sequence ",@(" in repl and .lisp buffers

### ISSUE THREAD

**Issue by anubav** [portacle/portacle#59]
I'm having some trouble splicing a list into a macro definition. For some reason, whenever I type the characters ",@(" in sequence either in a repl or a .lisp buffer, emacs throws up "Symbol's function definition is void: find" in the minibuffer. So, I can't type something like:

~~~~
(defmacro countdown `(reverse (list ,@(list 1 2 3))))
~~~~

I'm a bit new to emacs, so any advice would be much appreciated.

**Comment by Shinmera** [comment]
Can you do: `M-: (setq debug-on-error t)`

When you type the `,@(` afterwards and the error occurs, Emacs should open up a new buffer with a trace in it. Can you post that for me?

Also, I assume you are on Windows, is that right?

**Comment by anubav** [comment]
Yes, I'm on Windows. Here's the error:
~~~~
Debugger entered--Lisp error: (void-function find)
  find(slime-repl-mode (slime-repl-mode lisp-mode))
  paredit-detect-cl-macro-character(nil 40)
  paredit-space-for-delimiter-p(nil 40)
  paredit-insert-pair(nil 40 41 goto-char)
  paredit-open-round(nil)
  funcall-interactively(paredit-open-round nil)
  call-interactively(paredit-open-round nil nil)
  command-execute(paredit-open-round)
~~~~

**Comment by Shinmera** [comment]
Okey, thanks. I think I got a fix. Can you put the following into `portacle/config/user.el`:
```
(defun paredit-detect-cl-macro-character (endp delimiter)
  (when (cl-find major-mode '(slime-repl-mode lisp-mode))
    (if (not endp)
        (save-excursion
         (let ((1-back (char-before (point)))
               (2-back (char-before (- (point) 1))))
           (null (or (cl-macro-character-p (char-before (point)))
                     (cl-macro-character-p (char-before (1- (point))))))))
        t)))
```

**Comment by anubav** [comment]
It let's me put the left paren in now, but it creates a space after the "@" sign and throws the following error:
~~~~
Error running timer 'slime-process-available-input': (void-variable macro-char)
~~~~

I've attached a screenshot of the error trace. Thanks for your help!

![screenshot 1](https://user-images.githubusercontent.com/5231498/33857122-21522a3c-de90-11e7-9fa6-021f5c983a5c.png)

**Comment by Shinmera** [comment]
Hmm, I can't reproduce that. Does that happen even after you restart Portacle?

**Comment by anubav** [comment]
Yeah, it does. For what it's worhth, I installed portacle in the default directory and haven't fiddled with emacs config (user.el) except to change the color theme. Maybe, I'll try to reinstall portacle.

**Comment by Shinmera** [comment]
Nah, that won't help. It might be something related to Windows, though. I'll need to test in a VM tomorrow.

**Comment by anubav** [comment]
No problem. Thanks for the help.

**Comment by Shinmera** [comment]
Alright, can you try deleting the `user.el` again, running `M-x portacle-update` to update the sources, and then restarting? Things are fixed on my test machine now.

**Comment by anubav** [comment]
Perfect, works now. Thanks!
