### ISSUE TITLE
OS X Install: File cannot be copied to new folder

### ISSUE THREAD

**Issue by mdtdev** [portacle/portacle#65]
After downloading the current Portacle (2018.02.02; file: "mac-portacle.dmg") I double-clicked the dmg to open it and got the following window (which I assume is normal, although the "dropbox installer" title is new to me):

<img width="770" alt="port_dmg_open" src="https://user-images.githubusercontent.com/9751401/35762894-d0a0976a-086d-11e8-9927-0a41050a4913.png">

When I attempt to grab the folder "portacle" and move it to another folder, I get this error message:

<img width="603" alt="port_err_msg" src="https://user-images.githubusercontent.com/9751401/35762899-f63b31a6-086d-11e8-9895-8939b260a48b.png">

...and that is the end. I cannot drag and drop it to another folder, I cannot copy and paste it, either.

Macbook Pro, 2014, macOS High Sierra 10.13.3. Let me know if I can provide more details that would help! Thanks for this project, I look forward to getting it working.

**Comment by Shinmera** [comment]
The best I can guess is that the downloaded image got corrupted somehow. Try downloading it anew.

**Comment by mdtdev** [comment]
Huh. I guess my internet expectations have gotten so high that I did not even consider that. Both files are exactly the same size but you were right, another download worked. The bits, they were not equivalent. Thanks @Shinmera !

**Comment by Shinmera** [comment]
There's been other issues where that was the cause. I somehow get the feeling that github's servers aren't very reliable.
