### ISSUE TITLE
Running incorrectly on Windows 10

### ISSUE THREAD

**Issue by Jungorend** [portacle/portacle#69]
Running portacle on Windows 10 worked appropriately until a recent update. Now when it loads, the screen does come up however the messages bar shows:

``apply: Opening process input file: No such file or directory, NUL: ``

![portacle-ts](https://user-images.githubusercontent.com/1012488/38179384-aa4f8dea-35f0-11e8-839e-f3d5bd0c9ffb.png)

You also get this message if you try to run commands such as 'package-refresh'.  Slime is missing.

I have redownloaded the most recent version, and tried it in compatibility modes for both Windows 7 and 8. I have also tried running it as an administrator.

**Comment by Shinmera** [comment]
I cannot reproduce your issue on a clean Windows 10 and Portacle installation.

**Comment by Jungorend** [comment]
I am not able to reproduce it on other machines either. It must be a fluke of the windows environment I am on. Apologies.

**Comment by Shinmera** [comment]
I'm really puzzled as to what might be causing this though. My only idea is either bad permissions or a missing `.portacle_root` file, but then emacs shouldn't launch at all either, so I don't know.
