### ISSUE TITLE
hunspell is not being installed properly on OS X

### ISSUE THREAD

**Issue by metayan** [portacle/portacle#72]
```
Error enabling Flyspell mode:
(portacle/mac/bin/hunspell exited with signal Trace/BPT trap: 5)
```
is shown every time a file is loaded into Emacs.

When run separately, with
```./package/portacle/mac/hunspell/bin/hunspell```
 it gives the following error:
```
dyld: Library not loaded: @loader_path/../../lib/libhunspell-1.6.0.dylib
  Referenced from: portacle/./package/portacle/mac/hunspell/bin/hunspell
  Reason: image not found
Trace/BPT trap: 5
```
Using OS X El Capitan (10.11.6) with Homebrew.

**Comment by Shinmera** [comment]
I can't reproduce your issue with the [1.1b release](https://github.com/portacle/portacle/releases/tag/1.1b)
