### ISSUE TITLE
Fails to open on MacOSX 10.11.6 with unsupported OS message

### ISSUE THREAD

**Issue by stephensmith9** [portacle/portacle#73]
Followed the instructions on the website to move the Portacle.app folder out and back in. Then opened with Ctrl-click (and also right-clicked to open) to bypass unidentified dev error. Getting this message now:

`You have OS X 10.11.6. The application requires OS X 10.12 or later.`

Has this recently changed? The website says it supports 10.11+.

**Comment by stephensmith9** [comment]
Thanks Nicolas, and thanks for such a useful application!

**Comment by Shinmera** [comment]
Here's the promised 1.1b build for 10.11. https://github.com/portacle/portacle/releases/download/1.1b/mac-portacle.dmg

Let me know if it works.
