### ISSUE TITLE
Page fails to load after clicking hyperlink in latest portacle for MacOSX

### ISSUE THREAD

**Issue by stephensmith9** [portacle/portacle#74]
If I click on a hyperlink in the About Emacs screen, eww launches but the requested page does not load. This error appears in the minibuffer :
"error in process filter: This function requires Emacs to be compiled with libxml2"

Using the latest 1.1b version of portacle for mac built on April 9/18.
MacOSX 10.11.6 (El Capitan)

**Comment by Shinmera** [comment]
libxml2 is not included in Emacs on purpose to strip down dependencies.

**Comment by stephensmith9** [comment]
Ok, noted. Thanks.

**Comment by Shinmera** [comment]
We could potentially enable more emacs extensions now that the basic systems are in place to patch over OS differences, but doing so would require really extensive testing that I don't have the time for right now.

**Comment by stephensmith9** [comment]
Totally understand that.
