### ISSUE TITLE
portacle not working with emacs-dashboard.el

### ISSUE THREAD

**Issue by MartinBuchmann** [portacle/portacle#75]
While I really appreciate the amazing work you did with portacle, I want to change some customizations to my own habits. While this was pretty straight-forward so far, I failed activating [emacs-dashboard](https://github.com/rakanalh/emacs-dashboard) as my startup screen.

I added to my user.el file. The package was downloaded before without an error. 

    (use-package dashboard
        :config
        (dashboard-setup-startup-hook))

After restarting portacle there is no error in the *Message* buffer or anything. The dashboard just does not show up and there is no dashboard buffer in the buffer list. I looked in all portacle elisp files without finding anything preventing the dashboard to start up.

**Comment by Shinmera** [comment]
Hm, odd. Not sure what's going on with this at the moment, but I'll try to take a look before the next release.

**Comment by MartinBuchmann** [comment]
I had a second look in dashboard.el. `dashboard-setup-startup-hook` uses `command-line-args` to guess whether or not a filename was given. As portacle loads `emacs-init.el` dashboards startup command fails. I don't think there is much you can do. I will include the `add-hooks` explicitly in my `user.el`.

**Comment by Shinmera** [comment]
There is something I can potentially do, which is use the site-lisp mechanism of Emacs to load the Portacle extensions, rather than to explicitly load a custom init file. I'll have to look into that, though

**Comment by Shinmera** [comment]
I have implemented the site-lisp mechanism now. It'll be in the next 1.4 release, or you can build Portacle yourself to test it. If the problem persists, please reopen this issue.
