### ISSUE TITLE
Emacs hangs

### ISSUE THREAD

**Issue by metayan** [portacle/portacle#78]
Occasionally the Portacle Emacs just hangs while editing. SBCL keeps running fine, but Emacs becomes incommunicable. It can be brought to the foreground, but other than that, there is no response.

Have tried C-c C-c and C-g.

Earlier today I found `pkill -SIGUSR2 emacs`, which worked to make it interrupt and bring up a backtrace, after which I could continue using it, but now not even that works.

I'm attaching the crash file that was generated when I "Force Quit" Portacle.
[emacs-25.2_2018-04-19-211732_now.crash.txt](https://github.com/portacle/portacle/files/1929575/emacs-25.2_2018-04-19-211732_now.crash.txt)

When it's in the stuck state, I've also run `sample <pid of portacle>` and have several such files, but they're 200-370MB large, with enormous amounts of `mark_object` lines (sometimes more than 600k lines). I can make the sample files available for download if they can be of any use.

Running OS X El Capitan.
Portacle is built 2018-04-02 from source. No changes to init files.

**Comment by metayan** [comment]
Hang occurred once when scrolling the REPL with two fingers on touchpad on OS X El Capitan, but didn't manage to replicate after clean start of Portacle.

**Comment by Shinmera** [comment]
Hm. I heavily doubt this has anything to do with Portacle in specific. It might be an issue related to Emacs itself, but if you can't reproduce it then I'm afraid you won't be able to report there either.

**Comment by metayan** [comment]
I just added that particular incident, because it hung immediately after scrolling, which was the first time I've seen it hang as a direct response to some activity by me.
It keeps happening otherwise as well, but very sporadically.

**Comment by Shinmera** [comment]
Either way, there isn't anything that I'd know to do to fix this or debug this. You'll have to ask Emacs experts.
