### ISSUE TITLE
Not working on MacOS Sierra

### ISSUE THREAD

**Issue by Hexirost** [portacle/portacle#79]
Downloaded the portacle app via [link](https://portacle.github.io/#get-mac). When I tried to open it, it opens for a split second then closes with no error. I tried opening via terminal and got this error below.
 LSOpenURLsWithRole() failed with error -10810 for the file /Applications/portacle/Portacle.app.
I think it might be an error is related with my OS, but thats a pretty new version.

**Comment by Shinmera** [comment]
Did you follow the instructions it lists on the website?

**Comment by Hexirost** [comment]
Yeah, I moved the Portacle directory to application and allowed it to be run through the System Preferences and ran the portacle.app

**Comment by Shinmera** [comment]
That's not what the instructions say. You need to move the `Portacle.app` to a directory inside the `portacle/` and then back out again.

**Comment by Hexirost** [comment]
Opps I misread that part it works now thanks
