### ISSUE TITLE
./portacle.run doesn't launch after update, core dumped

### ISSUE THREAD

**Issue by Araly** [portacle/portacle#80]
I'm on Linux Manjaro, i3 community edition : `Linux araly-legion 4.15.18-1-MANJARO #1 SMP PREEMPT Thu Apr 19 09:05:40 UTC 2018 x86_64 GNU/Linux`

After an update today, portacle doesn't launch anymore. When running portacle/portacle.run, it fails to launch and throws this output : 
```
emacs: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
/usr/local/bin/portacle: line 7: 27562 Aborted                 (core dumped) "$ROOT/lin/launcher/portacle" "$@"
```

This happens in the current portacle installation I had, and in a brand new downloaded to test if I had broken it myself. I haven't tried building it from source, but it's the next thing I'll try, I'll report back on it.

portacle was working yesterday, as I was working with it.

**Comment by Shinmera** [comment]
Does it work with [1.1b](https://github.com/portacle/portacle/releases/tag/1.1b)?

**Comment by Araly** [comment]
doesn't work with 1.1b, same exact problem

**Comment by Shinmera** [comment]
Okey, that's a new failure then.

**Comment by Araly** [comment]
When trying to build from source, I don't have an easy access to the development files for ncurses x11 xpm gtk2 zlib pcre curl4 ssl gcrypt glfw3 liblzma, as I couldn't find them in the repositories (Manjaro or AUR), and the build fails, finishing with this as an output : 
```
HEAD is now at 503e4f2 Define nss module stubs for modules that exist on systemd systems, but not on older systems. This should solve portacle/portacle#68
   ->  prepareing launcher
     >  skipping prepare, not needed
   ->  building launcher
cc -o "build/ld-wrap.so" -std=c99 -Wall -D_GNU_SOURCE -fPIC -shared -Wl,-init,init "src/ld-wrap.c" -ldl
src/ld-wrap.c: In function ‘ld_wrap_static_p’:
src/ld-wrap.c:85:29: warning: passing argument 2 of ‘o_execve’ from incompatible pointer type [-Wincompatible-pointer-types]
     return o_execve(loader, argv, env);
                             ^~~~
src/ld-wrap.c:85:29: note: expected ‘char * const*’ but argument is of type ‘const char * const*’
cc -o "build/libnss_mymachines.so.2" -std=c99 -Wall -D_GNU_SOURCE -D MODULE=mymachines -fPIC -shared "src/nss_stub.c" -lnss_dns
cc -o "build/libnss_myhostname.so.2" -std=c99 -Wall -D_GNU_SOURCE -D MODULE=myhostname -fPIC -shared "src/nss_stub.c" -lnss_dns
cc -o "build/libnss_resolve.so.2" -std=c99 -Wall -D_GNU_SOURCE -D MODULE=resolve -fPIC -shared "src/nss_stub.c" -lnss_dns
cc -o "build/portacle" -std=c99 -Wall -D_GNU_SOURCE -static "src/portacle.c"
cc -o "build/credentials" -std=c99 -Wall -D_GNU_SOURCE "src/portacle_credentials.c" -lglfw -lGL -lm -lGLU -lgcrypt
src/portacle_credentials.c:11:10: fatal error: GLFW/glfw3.h: No such file or directory
 #include <GLFW/glfw3.h>
          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:30: lin] Error 1

```

I'll try searching for the development files as that could be my problem another day, until then, I hope this can be of some use

**Comment by Shinmera** [comment]
Well, trying to build with missing dependencies is obviously going to fail.

**Comment by Shinmera** [comment]
I don't know about Manjaro, but on Arch I have no problem with the dependencies at all. The packages include the header files already.

**Comment by Shinmera** [comment]
Okey, since this might have been related to #63, can you please test the [1.1c release](https://github.com/portacle/portacle/releases/tag/1.1c)?

**Comment by Araly** [comment]
new 1.1c release works as intended, nice job :3
