### ISSUE TITLE
macOS font size from user.el not applied

### ISSUE THREAD

**Issue by ijean** [portacle/portacle#81]
Hello,

I've added this line in config/user.el:

(set-default-font "Monaco 14")

but it is not applied when Portacle starts. I know the above line should work because if I execute it from the running app (in the Elisp scratch buffer) the font and size is changed.

**Comment by Shinmera** [comment]
Please see portacle/config#1

**Comment by ijean** [comment]
Thanks.

**Comment by ernestocr** [comment]
I'm new to lisp and emacs, is there any documentation on how to configure elisp, specifically changing the font size?

**Comment by Shinmera** [comment]
https://github.com/portacle/portacle/issues/41#issuecomment-411131078
