### ISSUE TITLE
Portacle hangs on console startup, but only after playing certain DirectX games.

### ISSUE THREAD

**Issue by LambdaLord** [portacle/portacle#84]
Platform: Win10

Everything works fine after a fresh boot. But after playing Spelunky HD, attempting to start portacle.exe causes it to hang with a blinking cursor on console. Tested twice immediately after booting, no other apps. This is not a joke.

**Comment by Shinmera** [comment]
What happens if you delete/rename `all/fonts`? Font registration seems to have been causing all sorts of problems for people for completely mysterious reasons.
