### ISSUE TITLE
Confusing start

### ISSUE THREAD

**Issue by joaotavora** [portacle/portacle#86]
I downloaded `lin-portacle.tar.xz`, uncompressed and clicked the file. Emacs opened and I got a REPL. But the startup text is weird ;-). 

In your elisp files, you should only `provide` features in the end, so that errors when loading those files are caught. In this case you used `loop` in line 62 of portacle-help.el, a macro that doesn't exist by default in emacs. 

Also two other issues: the font is variable width and you can see what happens when I enabled tool-bar-mode.

![screenshot at 2018-06-11 12-07-18](https://user-images.githubusercontent.com/387011/41228498-7eed3bd6-6d70-11e8-9844-5620374f6da0.png)

**Comment by joaotavora** [comment]
I'll have a look at the font stuf. Probably something is going wrong, but you don't notice because every one of your .el files provides the feature at the top, ehehe :-)

**Comment by Shinmera** [comment]
From back when I had a look at it I could only surmise that it had something to do with the fonts having different family names sometimes and Emacs just defaulting to a variable-width one if it doesn't find the requested one. Might also be a problem with the font registration mechanism in the launcher, if the font doesn't get properly registered on the system, though that should work properly as far as I can tell.

**Comment by joaotavora** [comment]
Actually, just this seems to fix it
```diff
diff --git a/portacle-window.el b/portacle-window.el
index d597281..8353c06 100644
--- a/portacle-window.el
+++ b/portacle-window.el
@@ -1,5 +1,3 @@
-(provide 'portacle-window)
-
 (ensure-installed 'sublime-themes)
 
 (setq inhibit-startup-screen t)
@@ -15,7 +13,7 @@
   (scroll-bar-mode -1)
   (load-theme 'spolsky t)
   (setq confirm-kill-emacs 'y-or-n-p)
-  (add-to-list 'initial-frame-alist
+  (add-to-list 'default-frame-alist
                '(font . "Noto Mono-10:antialias=subpixel")))
 
 ;; http://directed-procrastination.blogspot.co.uk/2014/04/some-emacs-hacks-for-gdb-and-other-stuff.html
@@ -63,3 +61,6 @@ it will ask first)."
 (when window-system
   (add-hook 'emacs-startup-hook 'load-framegeometry)
   (add-hook 'kill-emacs-hook 'save-framegeometry))
+
+(provide 'portacle-window)
+
```

**Comment by joaotavora** [comment]
(but you should test)

**Comment by joaotavora** [comment]
(I'll make another pull request)
