### ISSUE TITLE
Install fonts into "default fonts directory"?

### ISSUE THREAD

**Issue by jkabrg** [portacle/portacle#89]
I tried working around issue #58 by deleting the fonts folder. Unfortunately, I'm finding that the fonts folder is being used by the System proces -- and so I can't delete it at the moment. This may be a relevant Stackoverflow:  https://stackoverflow.com/questions/27677285/font-file-is-being-held-by-system-process

At the end, it recommends putting the fonts into the "default fonts folder" (which I believe is `%windir%\fonts`). Maybe instead of putting the fonts into `all/fonts` folder, the fonts should be put into `%windir%\fonts`.

**Comment by Shinmera** [comment]
The problem with the default fonts folder is that it requires administrator privileges to change, and "poisons" the system with files from Portacle. You should be able to unlock the font again by a call to the Windows API `RemoveFontResource`. The launcher is currently not capable of doing that for you, unfortunately.

**Comment by jkabrg** [comment]
Don't know how to make API calls on Windows. What's the easiest way to do it?

**Comment by Shinmera** [comment]
Writing a C program. Would be easier to just reboot if all you want is to remove the directory.

**Comment by jkabrg** [comment]
OK. I managed to delete it. Anyway, Portacle still doesn't start. All I see is a terminal window, and nothing happens.

**Comment by jkabrg** [comment]
I guess it's not a fonts issue then...

**Comment by Shinmera** [comment]
Do you have a windows debugger that you can attach and get a stack trace from?

**Comment by Shinmera** [comment]
Just to keep the issues clean, since this is the same as #58, please continue the discussion there.
