### ISSUE TITLE
Crash on x86_64 Linux when typing certain strings in SLY REPL

### ISSUE THREAD

**Issue by stutonk** [portacle/portacle#91]
OS: Arch Linux `4.17.14-arch1-1-ARCH #1 SMP PREEMPT Thu Aug 9 11:56:50 UTC 2018 x86_64`

Using the latest release tarball and `portacle-update`, emacs crashes abruptly with the following error when typing certain sequences of characters at the SLY REPL prompt:
```
Inconsistency detected by ld.so: dl-open.c: 689: _dl_open: Assertion `_dl_debug_
initialize (0, args.nsid)->r_state == RT_CONSISTENT' failed!
```
The strings that cause the error are what you might commonly find at the beginning of a Common Lisp format specifier such as `"~{~` . It seems certain combinations of `"~` and two other characters (eg `"~~~`) will cause the crash where as some combinations do not (eg `"{~\\`). 

The crash does NOT occur when typing similar strings into the SLIME REPL.

**Comment by Shinmera** [comment]
Wew. Looks like Sly is trying to load shared libraries from the host at runtime. @joaotavora any ideas?

**Comment by joaotavora** [comment]
Sly is absolutely not loading any libraries. It's a 100 percent elisp application. Elisp does allow that in very recent versions but sly does not make use of this feature. Can you reproduce this? I'm away from my computer.

Running portable under strace or, better yet, under gdb, might be the thing to do

**Comment by stutonk** [comment]
At the time of error, `strace -e open` gives the following:
```
open("/etc/passwd", O_RDONLY|O_CLOEXEC) = 16
open("/home/stutonk/code/portacle//lin/lib/libnss_mymachines.so.2", O_RDONLY|O_C
LOEXEC) = 17
open("/home/stutonk/code/portacle//lin/lib/libnss_dns.so.2", O_RDONLY|O_CLOEXEC)
 = 17
open("/home/stutonk/code/portacle//lin/lib/libnss_systemd.so.2", O_RDONLY|O_CLOE
XEC) = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 17
open("/usr/lib/libnss_systemd.so.2", O_RDONLY|O_CLOEXEC) = 17
Inconsistency detected by ld.so: dl-open.c: 689: _dl_open: Assertion `_dl_debug_
initialize (0, args.nsid)->r_state == RT_CONSISTENT' failed!
+++ exited with 127 +++
```
Not an expert on this kind of issue but looks like something expects `libnss_systemd.so.2` to be present in the distribution. The inconsistency seems to be caused by `ld.so.cache` loading my system's copy of the library, which must be incompatible.

**Comment by Shinmera** [comment]
The problem is related to #68, so I guess I need to include another monkey-patch library for the (previously unseen) libnss_systemd.

**Comment by joaotavora** [comment]
@stutonk, can you run vanilla Emacs 26.1 in your system?

**Comment by stutonk** [comment]
Yes -- Do you want me to test those strings/SLY against that? And if so, what information should I collect?

**Comment by joaotavora** [comment]
Start by just checking whether it crashes  or not. If it does, it's a Sly/Emacs problem. If it doesn't it's possibly the way that portacle is built/distributed.

**Comment by Shinmera** [comment]
It is a Portacle problem. It's just that for some reason Sly causes nsswitch to be loaded, possibly due to a network request or some other action that would cause libc to open the file and load the various libnss_ parts, one of which is not yet patched with Portacle.

**Comment by joaotavora** [comment]
> It is a Portacle problem.

Whew :-) 

> Sly causes nsswitch.conf to be loaded, possibly due to a network request or some other action that would cause libc to open the file and load the various libnss_ parts

Indeed, that is curious in itself.  I ran my vanilla Emacs it doesn't load nsswitcch.conf, but in portacle it does, and precisely when @stutonk reports it. I'll investigate a bit more.
