### ISSUE TITLE
Can it work in no-window mode?

### ISSUE THREAD

**Issue by hajovonta** [portacle/portacle#93]
Hi,
I plan to run it on a VPS. Currently I get a nice window which is presented to me over ssh, but can I run it as I would in a terminal, e.g. emacs -nw, so that I get to work in emacs in console mode?
Thanks.
hajovonta

**Comment by Shinmera** [comment]
Theoretically it should be possible, but a short test right now reveals that there's problems with the terminfo database, so I'll have to investigate this and see what I need to do for it to be portlable.

**Comment by Shinmera** [comment]
Just to note, you can try this with either

    ./portacle.run emacs -nw

or

    ./lin/bin/emacs -nw

**Comment by hajovonta** [comment]
Yes, it worked. Thank you!
