### ISSUE TITLE
Cannot pass runtime options to sbcl

### ISSUE THREAD

**Issue by jasom** [portacle/portacle#99]
Any args passed to the sbcl launcher come after `--nosysinit` and `--userinit` which are toplevel options; runtime options cannot appear after toplevel options.

In this case, I wanted to change the dynamic space size.

I think the best solution might be to put all arguments before the arguments added by the portacle launcher, but am up for other possibilites.

**Comment by Shinmera** [comment]
That won't work in case you want to pass user args for your script or something like that.

**Comment by jasom** [comment]
The simplest option I can currently think of then would be to search for `--` as an option and prepend everything before the `--`.

The most ergonomic option would probably be to scan for any known runtime options and prepend them.  That's a lot more work though.

**Comment by blindglobe** [comment]
I'm being clueless at this point, but where would I make the change to change the sbcl options to take advantage of this change?  (specifically the dynamic-space-size, specifically under Microsoft Windows 10).    I was looking around for a place to modify in the elisp files, but could not figure out what exactly to change?

**Comment by Shinmera** [comment]
https://github.com/portacle/emacsd/blob/master/portacle-slime.el#L43

As usual in slime. However, I don't think this patch is in the latest Portacle yet, so you would have to compile the launcher yourself and replace the respective binaries.
